var currencies = [
  { unit: "USD", name: "Amerikan Doları" },
  { unit: "CHF", name: "Swiss Franc" },
  { unit: "AED", name: "Birleşik Arap Emirlikleri Dirhemi" },
  { unit: "SEK", name: "İsveç Kronu" },
  { unit: "KWD", name: "Kuveyt Dinarı" },
  { unit: "LYD", name: "Libya Dinarı" },
  { unit: "ILS", name: "Yeni İsrail Şekeli" },
  { unit: "MXN", name: "Meksika Pesosu" },
  { unit: "BRL", name: "Brezilya Reali" },
  { unit: "PLN", name: "Polonya Zlotisi" },
  { unit: "ARS", name: "Arjantin Pesosu" },
  { unit: "BAM", name: "Bosna-Hersek Markı" },
  { unit: "CRC", name: "Kosta Rika Kolonu" },
  { unit: "HKD", name: "Hong Kong Doları" },
  { unit: "HRK", name: "Hırvat Kunası" },
  { unit: "ISK", name: "İzlanda Kronu" },
  { unit: "JOD", name: "Ürdün Dinarı" },
  { unit: "KRW", name: "Güney Kore Wonu" },
  { unit: "KZT", name: "Kazakistan Tengesi" },
  { unit: "LBP", name: "Lübnan Lirası" },
  { unit: "LKR", name: "Sri Lanka Rupisi" },
  { unit: "MAD", name: "Fas Dirhemi" },
  { unit: "MDL", name: "Moldova Leyi" },
  { unit: "MKD", name: "Makedonya Dinarı" },
  { unit: "MYR", name: "Malezya Ringgiti" },
  { unit: "OMR", name: "Umman Riyali" },
  { unit: "PEN", name: "Peru Solü" },
  { unit: "PHP", name: "Filipin Pesosu" },
  { unit: "PKR", name: "Pakistan Rupisi" },
  { unit: "QAR", name: "Katar Riyali" },
  { unit: "RSD", name: "Sırp Dinarı" },
  { unit: "SGD", name: "Singapur Doları" },
  { unit: "SYP", name: "Suriye Lirası" },
  { unit: "THB", name: "Tayland Bahtı" },
  { unit: "TWD", name: "Yeni Tayvan Doları" },
  { unit: "UAH", name: "Ukrayna Grivnası" },
  { unit: "UYU", name: "Uruguay Pesosu" },
  { unit: "GEL", name: "Gürcistan Larisi" },
  { unit: "TND", name: "Tunus Dinarı" },
  { unit: "BGN", name: "Bulgar Levası" },
  { unit: "ONS", name: "ONS Altın" },
  { unit: "GRA", name: "Gram Altın" },
  { unit: "CEY", name: "Çeyrek Altın" },
  { unit: "YAR", name: "Yarım Altın" },
  { unit: "TAM", name: "Tam Altın" },
  { unit: "CUM", name: "Cumhuriyet Altını" },
  { unit: "ATA", name: "Ata Altın" },
  { unit: "RES", name: "Reşat Altın" },
  { unit: "HAM", name: "Hamit Altın" },
  { unit: "IKI", name: "İki Buçuk Altın" },
  { unit: "GRE", name: "Gremse Altın" },
  { unit: "BES", name: "Beşli Altın" },
  { unit: "ODA", name: "14 Ayar Altın" },
  { unit: "OSA", name: "18 Ayar Altın" },
  { unit: "YIA", name: "22 Ayar Bilezik" },
  { unit: "GUM", name: "Gümüş" },
];